//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HunspellSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HunspellSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affix {0} is corrupt.
        /// </summary>
        internal static string AffixCorrupted {
            get {
                return ResourceManager.GetString("AffixCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad flag vector.
        /// </summary>
        internal static string BadFlagvector {
            get {
                return ResourceManager.GetString("BadFlagvector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hzip password is missing or invalid.
        /// </summary>
        internal static string BadPassword {
            get {
                return ResourceManager.GetString("BadPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty .dic file.
        /// </summary>
        internal static string EmptyDic {
            get {
                return ResourceManager.GetString("EmptyDic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible stripping characters and condition.
        /// </summary>
        internal static string IncompatibleCondition {
            get {
                return ResourceManager.GetString("IncompatibleCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing ] in condition: {0}.
        /// </summary>
        internal static string IncompleteCondition {
            get {
                return ResourceManager.GetString("IncompleteCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaking infinite loop.
        /// </summary>
        internal static string InfiniteLoop {
            get {
                return ResourceManager.GetString("InfiniteLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of entries.
        /// </summary>
        internal static string InvalidEntriesNumber {
            get {
                return ResourceManager.GetString("InvalidEntriesNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of fields.
        /// </summary>
        internal static string InvalidFieldsNumber {
            get {
                return ResourceManager.GetString("InvalidFieldsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid flag vector alias index: {0}.
        /// </summary>
        internal static string InvalidFlagAliasIndex {
            get {
                return ResourceManager.GetString("InvalidFlagAliasIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAG needs `num&apos;, `long&apos; or `UTF-8&apos; parameter.
        /// </summary>
        internal static string InvalidFlagMode {
            get {
                return ResourceManager.GetString("InvalidFlagMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing or bad word count in the .dic file.
        /// </summary>
        internal static string InvalidInitialWordCount {
            get {
                return ResourceManager.GetString("InvalidInitialWordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid morph. alias index: {0}.
        /// </summary>
        internal static string InvalidMorphAliasIndex {
            get {
                return ResourceManager.GetString("InvalidMorphAliasIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0}: {1}.
        /// </summary>
        internal static string MessageWithLineNumber {
            get {
                return ResourceManager.GetString("MessageWithLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing compoundsyllable information.
        /// </summary>
        internal static string MissingCompoundsyllableInfo {
            get {
                return ResourceManager.GetString("MissingCompoundsyllableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is missing.
        /// </summary>
        internal static string MissingData {
            get {
                return ResourceManager.GetString("MissingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple definitions of an affix flag.
        /// </summary>
        internal static string MultipleAffixFlag {
            get {
                return ResourceManager.GetString("MultipleAffixFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple definitions of {0}.
        /// </summary>
        internal static string MultipleDefinitions {
            get {
                return ResourceManager.GetString("MultipleDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream is not in hzip format or corrupted.
        /// </summary>
        internal static string NotHzipFormat {
            get {
                return ResourceManager.GetString("NotHzipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table is corrupt.
        /// </summary>
        internal static string TableCorrupted {
            get {
                return ResourceManager.GetString("TableCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affix length {0} is over max limit.
        /// </summary>
        internal static string TooLargeAffix {
            get {
                return ResourceManager.GetString("TooLargeAffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag id {0} is too large (max: {1}).
        /// </summary>
        internal static string TooLargeFlag {
            get {
                return ResourceManager.GetString("TooLargeFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .dic initial approximate word count line value of {0} is too large for {1} lines.
        /// </summary>
        internal static string TooLargeInitialWordCount {
            get {
                return ResourceManager.GetString("TooLargeInitialWordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word length {0} is over max limit.
        /// </summary>
        internal static string TooLongWord {
            get {
                return ResourceManager.GetString("TooLongWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file.
        /// </summary>
        internal static string UnexpectedEOF {
            get {
                return ResourceManager.GetString("UnexpectedEOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown encoding: &apos;{0}&apos;.
        /// </summary>
        internal static string UnknownEncodingError {
            get {
                return ResourceManager.GetString("UnknownEncodingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown encoding: &apos;{0}&apos;; using ISO-8859-1 as fallback.
        /// </summary>
        internal static string UnknownEncodingWarning {
            get {
                return ResourceManager.GetString("UnknownEncodingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 is wrong flag id.
        /// </summary>
        internal static string ZeroFlag {
            get {
                return ResourceManager.GetString("ZeroFlag", resourceCulture);
            }
        }
    }
}
